services:
  - type: web
    name: recipe-finder-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SPOONACULAR_API_KEY
        value: ${SPOONACULAR_API_KEY}
